ls:
    src:
        .dir: kebab-case
    src/components/containers/**/*:
        .dir: PascalCase | regex:__snapshots__
    src/components/layout/**/*:
        .dir: PascalCase | regex:__snapshots__
    src/components/ui/**/*:
        .dir: regex:\bV[A-Z][a-z]*([A-Z][a-z]*)*\b | regex:__snapshots__
    tests:
        .dir: kebab-case
    .ts: kebab-case
    .d.ts: kebab-case
    .test.ts: kebab-case
    .spec.ts: kebab-case
    .tsx: PascalCase
    .test.tsx: PascalCase
    .scss: kebab-case
    .module.scss: PascalCase
    .png: kebab-case
    .jpg: kebab-case

ignore:
    - _templates
    - .github
    - .husky
    - .lighthouseci
    - .next
    - .vscode
    - '@types'
    - coverage
    - node_modules
