name: Integration

on:
    pull_request:
        branches: [main]

jobs:
    test_pull_request:
        name: Testing & Checking the code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Installing dependencies
              run: yarn install --immutable --immutable-cache --check-cache

            - name: Check unused dependencies
              run: yarn run depcheck

            - name: Check Files and Directories Linter
              run: yarn run inflint

            - name: Check Typescript
              run: yarn run type-check

            - name: Check ESLint
              run: yarn run lint

            - name: Check Stylelint
              run: yarn run stylelint

            - name: Testing with coverage
              run: yarn run test:cov

            - name: Check build command
              run: yarn run build

            - name: Testing e2e
              run: yarn run test:e2e
